### ISSUE TITLE
Integrate test vectors into test suite

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-ecdsa-test-suite#29]
The test vectors here:

https://github.com/w3c/vc-di-ecdsa/tree/main/TestVectors

Should be integrated into this test suite in some way such that implementers that plug into the test suite can check their implementations against them.

**Comment by aljones15** [comment]
related issue: https://github.com/w3c/vc-di-ecdsa-test-suite/issues/49

**Comment by BigBlueHat** [comment]
@aljones15 now that #49 is merged, is this completed?

**Comment by aljones15** [comment]
@BigBlueHat so not quite, we do use some of @Wind4Greg 's vectors, but it turned out that the previous maintainer's vectors were more detailed, the test project is configurable enough that you could use the spec's text vectors in many places if wanted, but the spec's test vectors were not a 1-for-1 replacement for the existing vectors. Also many of the spec test vectors are unit or integration test level vectors and we end test at the VC API level so not sure that all vectors can be used from the spec's test vectors, but if you want to use them you can. @dlongley @Wind4Greg can we close this issue?

**Comment by Wind4Greg** [comment]
@aljones15, yes its okay to close. The test vectors in the specification are to guide developers and would not be a complete set of unit or integration test vectors

**Comment by aljones15** [comment]
closing as the spec's test vectors are more unit test level and this test suite is more of an end test.
