### ISSUE TITLE
Incorrect hashing used in tests for `ecdsa-rdfc-2019` `P-384`

### ISSUE THREAD

**Issue by sbihel** [w3c/vc-di-ecdsa-test-suite#86]
Hiya, the following tests are failing for `P-384` with our implementation:
- `ecdsa-rdfc-2019 (issuers) VC 1.1` `The "proof" MUST verify with a conformant verifier.`
- `ecdsa-rdfc-2019 (issuers) VC 2.0` `The "proof" MUST verify with a conformant verifier.`
- `ecdsa-rdfc-2019 (verifiers 1.1)` `MUST verify a valid VC with an ecdsa-rdfc-2019 proof.`
- `ecdsa-rdfc-2019 (verifiers 2.0)` `MUST verify a valid VC with an ecdsa-rdfc-2019 proof.`

After trying some random things, I noticed that if we used SHA-256 for [the hash data](https://w3c.github.io/vc-di-ecdsa/#hashing-ecdsa-rdfc-2019) instead of SHA-384 for P-384 keys, then all the tests would pass. So I'm assuming that the implementation used by the tests is incorrect, but maybe our interpretation of the specs is wrong?

**Comment by aljones15** [comment]
Your interpretation is probably correct:

> This specification uses either the RDF Dataset Canonicalization Algorithm [[RDF-CANON](https://w3c.github.io/vc-di-ecdsa/#bib-rdf-canon)] or the JSON Canonicalization Scheme [[RFC8785](https://w3c.github.io/vc-di-ecdsa/#bib-rfc8785)] to transform the input document into its canonical form. It uses one of two mechanisms to digest and sign: SHA-256 [[RFC6234](https://w3c.github.io/vc-di-ecdsa/#bib-rfc6234)] as the message digest algorithm and ECDSA with Curve P-256 as the signature algorithm, or SHA-384 [[RFC6234](https://w3c.github.io/vc-di-ecdsa/#bib-rfc6234)] as the message digest algorithm and ECDSA with Curve P-384 as the signature algorithm.

I'll look into this when I get a chance, but I think you're correct here and the problem is either that our verifier is incorrect or the implementation is incorrect. the implementation was use locally is DB's: https://github.com/digitalbazaar/ecdsa-rdfc-2019-cryptosuite/tree/main/lib

Thanks for the bug report.

**Comment by aljones15** [comment]
@sbihel if you can supply a VC signed with your implementation's p-384 key, I can run it through our stuff locally and debug a bit faster.

**Comment by aljones15** [comment]
Just so this known: here is the ecdsa-rdfc-2019 verifier code: https://github.com/digitalbazaar/ecdsa-multikey/blob/41c5a490a7acbf0fc11d37789768c27cdc1b73f3/lib/factory.js#L29-L50

And when it sees a P-384 it should be using the correct hash, so the issue might be that our implementation's publicKey algorithm is finding the wrong curve.

Interestingly the test project for ecdsa multikey does not actuall have a test to ensure that createVerifier works with P-384 so I'll start with adding that: https://github.com/digitalbazaar/ecdsa-multikey/blob/41c5a490a7acbf0fc11d37789768c27cdc1b73f3/test/EcdsaMultikey.spec.js#L29

**Comment by aljones15** [comment]
@sbihel just so you know a PR was merged to improve the test suite of `ecdsa-multikey` on our side. That pr does not show any regressions such as incorrect hashing, so that probably means the bug is in the test suite or your implementation. Taken that the prefix of your did key shows the correct header for P-384 I'm not sure on where the bug is coming from. the primary reason for this message is just to let you know that all of the current test developers are in a sprint that won't be over for a few weeks and no one has time to look at this bug right now so if you have a moment to track it down, please do. 

You can check the test project here: https://github.com/digitalbazaar/ecdsa-multikey
Which in turn will depend on:
https://github.com/digitalbazaar/ecdsa-rdfc-2019-cryptosuite
which in turn is used by:
https://github.com/digitalbazaar/vc/tree/update-vc-2.0
which is then used by:
https://github.com/w3c/vc-di-ecdsa-test-suite/blob/main/tests/vc-verifier/index.js

**Comment by aljones15** [comment]
@sbihel a patch release was made to our libraries WRT to the hash used for the P-384 keys: https://github.com/digitalbazaar/ecdsa-rdfc-2019-cryptosuite/blob/main/CHANGELOG.md

This might be relevant to your issue.

**Comment by sbihel** [comment]
Indeed, thank you.

**Comment by aljones15** [comment]
@sbihel I'm assuming it fixed your issue?

**Comment by sbihel** [comment]
Yes sorry I wasn't very clear. I tested the latest `main` of this test suite today and all the tests passed
